### ISSUE TITLE
Manifest file not found

### ISSUE THREAD

**Issue by zbigniew-malinowski** [alexfu/androidautoversion#34]
I'm using `com.android.tools.build:gradle:3.3.0-alpha13`.
When I added androidautoversion plugin (3.0.0) to my project, the build (eg. assembleRelease) fails with the stack trace below.

Any ideas?

```
Execution failed for task ':app:processReleaseManifest'.
> java.io.FileNotFoundException: property(interface org.gradle.api.file.Directory, transform(property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultProjectLayout$FixedDirectory, /Users/zb/StudioProjects/myproject/app/build))))/AndroidManifest.xml (No such file or directory)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processReleaseManifest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: property(interface org.gradle.api.file.Directory, transform(property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultProjectLayout$FixedDirectory, /Users/zb/StudioProjects/myproject/app/build))))/AndroidManifest.xml (No such file or directory)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:161)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: java.io.FileNotFoundException: property(interface org.gradle.api.file.Directory, transform(property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultProjectLayout$FixedDirectory, /Users/zb/StudioProjects/myproject/app/build))))/AndroidManifest.xml (No such file or directory)
        at com.github.alexfu.AndroidAutoVersionPlugin$_applyVersion_closure4$_closure5$_closure6.doCall(AndroidAutoVersionPlugin.groovy:75)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:739)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:712)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        ... 38 more

```

**Comment by kishangpt** [comment]
@zbigniew-malinowski Is your issue fixed ?? I am facing the same issue. How to fix it ??

**Comment by zbigniew-malinowski** [comment]
@kishangpt I ended up writing a simple helper reusing only `Version.groovy` file from this repo, more or less like this (it lives in one of my project's gradle files):

```
import groovy.json.JsonSlurper

ext {
    File versionFile = project.file("version.json")
    version = new Version(versionFile)
    project.task("bumpPatch").doLast {
        version.update(VersionType.PATCH)
    }

    project.task("bumpMinor").doLast {
        version.update(VersionType.MINOR)
    }

    project.task("bumpMajor").doLast {
        version.update(VersionType.MAJOR)
    }
    android.defaultConfig {
        versionCode = version.versionCode
        versionName = version.versionName
    }
}

task commitAndTag << {
    def file = project.file("version.json")
    if (!file.exists()) {
        throw new IllegalStateException("'version.json' file not found in root directory")
    }
    def json = new JsonSlurper().parseText(file.text)
    def version = "$json.major.$json.minor.$json.patch"
    println "committing version bump to $version"
    grgit.commit {
        message = "bumped version to $version"
        all = true
    }
    grgit.tag.add {
        name = version
    }
}

bumpPatch.finalizedBy commitAndTag
bumpMinor.finalizedBy commitAndTag
bumpMajor.finalizedBy commitAndTag
```

**Comment by kishangpt** [comment]
@zbigniew-malinowski I think you misunderstood the problem with some other problem ? The issue here is the path of the merged manifest file is not picked properly. 

 org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: property(interface org.gradle.api.file.Directory, transform(property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultProjectLayout$FixedDirectory, /Users/zb/StudioProjects/myproject/app/build))))/AndroidManifest.xml (No such file or directory)

Correct me if I am missing something here...!!

**Comment by zbigniew-malinowski** [comment]
@kishangpt Because of that issue, I was unable to use this plugin as is. 

However, I didn't see why reading the manifest is necessary here, so instead of fixing the code that read it, I just reused a subset of it that was actually useful.

**Comment by ewoks** [comment]
@kishangpt :
> _"The issue here is the path of the merged manifest file is not picked properly."_

👍

@zbigniew-malinowski 
> _"I didn't see why reading the manifest is necessary here. ... I just reused a subset of it that was actually useful"_

Did you make your own fork? My understanding is that reading/writing manifest is here to save correct build number in final AndroidManifest that will be packed in artefact apk.  


🚨
This issue is open for quite some time now and renders plugin completely incompatible with Gradle > 5.0. 
As a consequence **this plugin can't be used with Android Studio 3.4** which requires Gradle 5.1.1 when used with com.android.tools.build:gradle:3.4.0

would using following instead of `new File("$manifestOutputDirectory/AndroidManifest.xml")` solve the issue:
`new File(output.processManifest.manifestOutputDirectory.get().asFile, "AndroidManifest.xml")` ?

I opened [PR](https://github.com/alexfu/androidautoversion/pull/37) with hope this simple issue can be resolved. 
Tested it locally (from mavenLocal) and I could build my Android project again with dependencies described in PR

Anyone can take a look and ping maintainer please? cc: @alexfu , @ChrisGuzman , @jamesmosier @ravidsrk
